### ISSUE TITLE
sorry, how i can join on button click event? You can write a code?

### ISSUE THREAD

**Issue by alessiobb1** [sudopigeek/CGUI#1]
protected override void Run()
        {
          if (task == "0")
            {
                Label label0 = new Label("Loading Language anche se è gia in italiano di default. ma va bhe ", Color.White, 10, 10);
                Label label = new Label("Caricamento del font.. ", Color.White, 10, 30);
                Label label1 = new Label("... ", Color.Blue, 10, 50);
                Label label12 = new Label("...", Color.Blue, 10, 70);
              x
                s.Controls.Add(label);
                s.Controls.Add(label1);
                s.Controls.Add(label12);
                s.Controls.Add(label2);
                driver.RenderScreen(s);
                task = "1";
                Button button = new Button("Premi invio", 10, 120);
}
}
}

And now if i want be add "  Label label5 = new Label("desktop caricato.. ", Color.White, 10, 90);
                Screen s1 = new Screen();
                s1.Controls.Add(label5);"

Tranks!!!
Sorry for my english but i italian and i'm 13.. then is hard for me..

**Comment by sudopigeek** [comment]
You are close. To use the button's event, you have to "attach" the button's OnEnter event to a method called "Button_OnEnter":
```c#
button.OnEnter += Button_OnEnter;
```
Then, put this method in your class:
```c#
private void Button_OnEnter(object sender, EventArgs e)
{
            
}
```
Put in that method whatever you want to run when the user hits the enter or return key, and you're done!

**Comment by alessiobb1** [comment]
Now if i insert this code i receive 1 error "nvme.exe is finished with code 1. during the compilation"

**Comment by alessiobb1** [comment]
And if i delete che button code is starting without problem.. why?

**Comment by alessiobb1** [comment]
Only button.OnEnter += Button_OnEnter; will stop the complilation..wtf

**Comment by sudopigeek** [comment]
Are you using a release of CGUI or a clone?

**Comment by sudopigeek** [comment]
Download version 1.2.1; I fixed the issues you were having. Here is a working example:
```c#
public class Kernel : Sys.Kernel
    {
        VGADriver driver;
        Screen s = new Screen();
        protected override void BeforeRun()
        {
            driver = new VGADriver();
        }

        protected override void Run()
        {
            Label label0 = new Label("Loading Language anche se è gia in italiano di default. ma va bhe ", Color.White, 10, 10);
            Label label = new Label("Caricamento del font.. ", Color.White, 10, 30);
            Label label1 = new Label("... ", Color.Blue, 10, 50);
            Label label12 = new Label("...", Color.Blue, 10, 70);
            Button button = new Button("Premi invio", 10, 120);
            button.OnEnter += Button_OnEnter;
            s.Controls.Add(label);
            s.Controls.Add(label1);
            s.Controls.Add(label12);
            s.Controls.Add(label0);
            s.Controls.Add(button);
            driver.RenderScreen(s);
        }

        private void Button_OnEnter(object sender, EventArgs e)
        {
            driver.ClearScreen();
            Label label5 = new Label("desktop caricato.. ", Color.White, 10, 90);
            Screen s1 = new Screen();
            s1.Controls.Add(label5);
            driver.RenderScreen(s1);
            // and so on...
        }
    }
```
Also make sure you follow the proper order: 1) declare the controls, 2) add them to the screen, 3) render it.

**Comment by alessiobb1** [comment]
Thanks a lot! Now I'll try if it works, sorry if I bothered you, what time zone are you so I don't bother you at night .. because yesterday you woke me up at 5 am for the email of the message .. hahah

**Comment by alessiobb1** [comment]
Where is the updated version= I don't find is.. you can send the link to downlad of 2.21.. tranks a lot!

**Comment by sudopigeek** [comment]
No problem

**Comment by alessiobb1** [comment]
why if i insert the button, the vm lag? i sent video to you .. wait

**Comment by alessiobb1** [comment]
Why if i insert button the os freeze? And not responding?

**Comment by sudopigeek** [comment]
How did you declare the button? The code I posted above doesn't freeze

**Comment by alessiobb1** [comment]
Then i may adapt the my os in the your code! And what the your time zona? i'm in +1, you? then i don't get up by the bed you.. hahah

**Comment by sudopigeek** [comment]
My time zone is -6

**Comment by alessiobb1** [comment]
Sorry, you can read this my code.. why post login "Accedi come.." dont load the desktop but load a blank black screen.
`using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using CGUI;
using System.Drawing;

namespace AleCOS2
{
    public class Kernel : Sys.Kernel
    {
        VGADriver driver;
        Screen s = new Screen();
        string task = "0";
        string ver = "2047a";
        protected override void BeforeRun()
        {
            driver = new VGADriver();
        }

        protected override void Run()
        {
            if (task == "0")
            {
                Label label01 = new Label("Avvio di AleCOS  " + ver, Color.Red, 10, 10);
                Label label0 = new Label("Loading Language anche se e' gia in italiano di default. ma va bhe ", Color.White, 10, 80);
                Label label = new Label("Caricamento del font.. ", Color.White, 10, 100);
                Label label1 = new Label("Grazie YoungTech per aver realizzato questo video. e metto questo disclamer", Color.Blue, 10, 250);
                Label label2 = new Label(" così i tuoi iscritti capiscolo che è stato fatto da un iscritto", Color.Blue, 10, 270);
                Label label12 = new Label("L' utente si chiama cosi' perche' ogni tuo utente e' cosi'", Color.Gray, 10, 310);
                s.Controls.Add(label01);
                s.Controls.Add(label);
                s.Controls.Add(label0);
                s.Controls.Add(label1);
                s.Controls.Add(label2);
                Button button = new Button("Accedi come Gianpierpaoloalessio", 10, 290);
                button.OnEnter += Button_OnEnter;
                s.Controls.Add(label);
                s.Controls.Add(label1);
                s.Controls.Add(label12);
                s.Controls.Add(label0);
                s.Controls.Add(button);
                driver.RenderScreen(s);
            }
            else if (task == "App")
            {
                Label label5 = new Label("AleCOS  2." + ver + " - ", Color.White, 10, 7);
                Label labMen1 = new Label(DateTime.Now.ToString(), 482, 7);
                Screen s1 = new Screen();

                s1.backColor = Color.Orange;
                s1.Controls.Add(labMen1);
                s1.Controls.Add(label5);
                Button button3 = new Button("Accedi come Gianpierpaoloalessio", 10, 290);
                button3.OnEnter += Button6_OnEnter;
                s.Controls.Add(button3);
                driver.RenderScreen(s1);
            }
            else if (task == "Set")
            {
                Label label5 = new Label("AleCOS  2." + ver + " - ", Color.White, 10, 7);
                Label labMen1 = new Label(DateTime.Now.ToString(), 472, 7);
                Screen sSet = new Screen();
                Label labSet1 = new Label("Schermo", 10, 20);
                sSet.backColor = Color.Orange;
                sSet.Controls.Add(labSet1);
                sSet.Controls.Add(labMen1);
                sSet.Controls.Add(label5);
                Button button3 = new Button("X", 482, 7);
                button3.OnEnter += Button6_OnEnter;
                s.Controls.Add(button3);

                driver.RenderScreen(sSet);
            }
            else
                driver.ClearScreen();
                Label labelr = new Label(":( Si e' verificato un problema con le attivita' quindi bho  /nprova a riavviarmi", Color.White, 10, 30);
            Screen s2 = new Screen();
            s2.backColor = Color.Blue;
            s2.Controls.Add(labelr);
            driver.RenderScreen(s2);
        }

        private void Button_OnEnter(object sender, EventArgs e)
        {
            driver.ClearScreen();
            task = "App";
        }
      
        private void Button6_OnEnter(object sender, EventArgs e)
        {
            driver.ClearScreen();
            task = "App";
        }
      
    }
}
`

**Comment by sudopigeek** [comment]
The screen is black because your code gets to the ClearScreen() method in your button event, but it stays there because after it sets the task string's value, there is nothing more to run. To fix this, just put `Run();` in your events, right after you set the task string. When you run it, the code runs the main method again when the event is fired, sees that the task string is set to "App" instead of "0", and acts accordingly.

**Comment by alessiobb1** [comment]
It's work. thanks you! You know how do exemple: If i press "H" then Label lab = new Label("You pressed H",Color.Red,10,10) s.Controls.add(lab) s.RenderScreen(s);   how i may made if press * key then?

**Comment by sudopigeek** [comment]
When the button has focus?

**Comment by alessiobb1** [comment]
Yes. but in the buttons I can only press "Enter" instead of doing that if at any time I press a key it makes me an action .. you understand?

**Comment by alessiobb1** [comment]
The you second question is that i meant

**Comment by alessiobb1** [comment]
I have tried but is not working
 if (Console.KeyAvailable)
                        if (Console.ReadKey(true).Key == ConsoleKey.Spacebar)
                        {
                            task = "appSet";
                            Run();
                        }

**Comment by alessiobb1** [comment]
You have a answer? Tranks

**Comment by sudopigeek** [comment]
I will address this in the next release that will be uploaded in a few hours

**Comment by alessiobb1** [comment]
The new version resolved the  my problems.

**Comment by alessiobb1** [comment]
I have download.. post video-school  i try  the you release

**Comment by alessiobb1** [comment]
You have a exemple of code with press key H then 
Label lab = mew Label ("You have pressed H",10,10);
and so on.. So i understand..  Tranks!

**Comment by sudopigeek** [comment]
Here is your example:
```c#
using CGUI;
using Sys = Cosmos.System;
using System.Drawing;

namespace cguitest
{
    public class Kernel : Sys.Kernel
    {
        VGADriver driver;
        protected override void BeforeRun()
        {
            driver = new VGADriver();
        }

        protected override void Run()
        {
            Screen s = new Screen();
            Button button = new Button("Button", System.ConsoleKey.H, 60, 60);
            button.OnEnter += Button_OnEnter;
            s.Controls.Add(button);
            driver.RenderScreen(s);
        }

        private void Button_OnEnter(object sender, System.EventArgs e)
        {
            Screen s = new Screen();
            Label lab = new Label("You have pressed H", 10, 10);
            s.Controls.Add(lab);
            driver.RenderScreen(s);
        }
    }
}
```

**Comment by alessiobb1** [comment]
No, but make a two key press , exemply if press Enter make an object, if press Ctrl make a label.. is possibile?

**Comment by sudopigeek** [comment]
Not currently
