### ISSUE TITLE
Text not updating

### ISSUE THREAD

**Issue by Vardan2009** [sudopigeek/CGUI#12]
Here's my code:

string time = DateTime.Now.ToString();
Screen desk=new Screen();

Label l = new Label (time,10,10);

while(true){
time= DateTime.Now.ToString();
I.Update(time);
Driver.renderScreen(desk);
}

**Comment by sudopigeek** [comment]
Put the RenderScreen() method before the while loop, not in it. You also need to add the label to your screen (i.e. `desk.Controls.Add(l);`) before you render it.

**Comment by Vardan2009** [comment]
Oh ok, I'll try ;)

**Comment by Vardan2009** [comment]
I Updated My Code:

string time = DateTime.Now.ToString();
Screen desk=new Screen();

Label l = new Label (time,10,10);
Driver.renderScreen(desk);
s.Controls.Add(l);
while(true){
time= DateTime.Now.ToString();
I.Update(time);

}

It's Updating But Only On The First Frame

**Comment by Vardan2009** [comment]
What to do

**Comment by sudopigeek** [comment]
I'm working on it

**Comment by Vardan2009** [comment]
Ok
