### ISSUE TITLE
 desk.Controls.Remove(); Freezes the OS

### ISSUE THREAD

**Issue by Vardan2009** [sudopigeek/CGUI#14]
void Menuu(object sender, EventArgs e)
        {
            menuact = !menuact;
            if (menuact)
            {
                desk.Controls.Add(menu);
                desk.Controls.Add(Sysprefs);
                desk.Controls.Add(Tools);
                desk.Controls.Add(About);
                driver.RenderScreen(desk);
            }
            else
            {
                desk.Controls.Remove(menu);
                desk.Controls.Remove(Sysprefs);
                desk.Controls.Remove(Tools);
                desk.Controls.Remove(About);
              
                driver.RenderScreen(desk);
            }
           
        }

when I Click the button once it shows up, but when i click it again, instead of dissapearing the OS freezes

**Comment by sudopigeek** [comment]
Since the screen is already rendered, try using UpdateScreen() instead of RenderScreen() and see if it makes a difference.

**Comment by Vardan2009** [comment]
Ok, I'll try later

**Comment by Vardan2009** [comment]
I Updated The Code:

  menuact = !menuact;
            if (menuact)
            {
                desk.Controls.Add(menub);
                desk.Controls.Add(Sysprefs);
                desk.Controls.Add(Toolss);
                desk.Controls.Add(About);
                driver.RenderScreen(desk);
            }
            else
            {

                desk.Controls.Remove(menub);
                desk.Controls.Remove(Sysprefs);
                desk.Controls.Remove(Toolss);
                desk.Controls.Remove(About);
                driver.UpdateScreen();
            }

But it freezes again

**Comment by Vardan2009** [comment]
:|

**Comment by sudopigeek** [comment]
Sorry for the delay. I fixed the issue and will be making a new release soon, but if you want it now, you can get the updated DLL from the repo [here](https://raw.githubusercontent.com/sudopigeek/CGUI/main/CGUI/bin/Debug/netcoreapp2.0/CGUI.dll).

**Comment by Vardan2009** [comment]
Thanks!
