### ISSUE TITLE
image dont have Fromfile

### ISSUE THREAD

**Issue by boyangsic** [sudopigeek/CGUI#2]
sorry for stupid question

**Comment by sudopigeek** [comment]
Are you using a release or a clone of the repo?

**Comment by boyangsic** [comment]
im using release

**Comment by sudopigeek** [comment]
It was a wiki mistake; it now shows the correct usage on the page [here](https://github.com/sudopigeek/CGUI/wiki/Picture).

**Comment by boyangsic** [comment]
But where i put bmp file? In project file? Or the virtual machines disk?

**Comment by sudopigeek** [comment]
For CGUI to read the bitmap, it has to be in the virtual machine's disk.
