### ISSUE TITLE
label.update bug

### ISSUE THREAD

**Issue by boyangsic** [sudopigeek/CGUI#3]
my code:

        string time = (DateTime.Now.ToString());

                Screen screen = new Screen();
                driver = new VGADriver();
                Label timelabel = new Label(time, 0, 0);
                screen.Controls.Add(timelabel);
                driver.RenderScreen(screen);
                while (true)

                {
                    timelabel.Update(time);

                }
and it say "No overload for method 'Update' takes 1 arguments".

**Comment by sudopigeek** [comment]
That shouldn't be an issue; the Update() method takes a string used for updating the label. As far as I can tell, there isn't anything in your code that would cause such an error; I tested it on my system and there isn't an issue. Strange

**Comment by boyangsic** [comment]
i  used newest ver and it fixed

**Comment by Vardan2009** [comment]
it not gives me an error but text is not updating xD
