### ISSUE TITLE
When making a menu, how can i use the enter button to select different buttons, to change to different screens?

### ISSUE THREAD

**Issue by octaviousrex** [sudopigeek/CGUI#8]
I have this so far:
```
            Label label_1 = new Label("Mini OS has booted successfully!\nSelect an option below.", Color.Green, 10, 10);
            // Adds a new Button
            Button btn_1 = new Button("Color Screen", 50, 50);
            Button btn_2 = new Button("About", 50, 100);
            Button btn_3 = new Button("Version", 50, 150);
            Button btn_4 = new Button("TBD", 50, 200);
            // Detects button press
            btn_1.OnEnter += Btn_OnEnter;
            btn_2.OnEnter += Btn_OnEnter;
            btn_3.OnEnter += Btn_OnEnter;
            btn_4.OnEnter += Btn_OnEnter;
```
and i noticed that when the ENTER button is pressed, it activates `private void Btn_OnEnter(object sender, EventArgs e)` (which opens a new screen with whatever i put on it) i plan on using a few screens, corresponding to their option button.
but the issue is, is that i have several buttons working to make a menu. so when i highlight an option, and hit enter, will it just try to open multiple?

**Comment by sudopigeek** [comment]
It sounds like you want to fire multiple button events when only one button is pressed, is that correct?

**Comment by octaviousrex** [comment]
I think i wrote that in a confusing way. I want to fire one button event, based on what button you highlight and press.

**Comment by sudopigeek** [comment]
Ah, you mean an Alt-like button selection method?
