### ISSUE TITLE
Bitmap Drawing Exception

### ISSUE THREAD

**Issue by Vardan2009** [sudopigeek/CGUI#9]
When I'm Trying to draw a bitmap , it gives me an Exception

Here's The Code

`  Bitmap bb = new Bitmap(@"C:\Users\user\Desktop\bitmapp.bmp");
   Picture picture = new Picture(bb, 100, 100);
   s.Controls.Add(picture);`

Thanks :)

**Comment by sudopigeek** [comment]
The bitmap must be on the filesystem of the OS (Cosmos) not the system that was used to compile it. See [this](https://github.com/CosmosOS/Cosmos/issues/1543) issue for more info on how to add it to Cosmos' virtual disk.

**Comment by octaviousrex** [comment]
Originally, i tried adding the bitmap image as a resource but found this to not work. I found the linked issue on the comment above, and i think that is the best solution (and a good solution for a lot of things)
